.TH SUNXI-SCRIPT_EXTRACTOR "8" "January 2016" "Sunxi-Tools for allWinner's devices"
.SH NAME
sunxi-script_extractor \- Extract script.bin blob from RAM on android devices.
.SH SYNOPSIS
.TP
.B sunxi-script_extractor
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
A simple tool, which can be executed on a rooted Android device to dump the script.bin blob from RAM via reading /dev/mem.
.PP
Compiled as a static binary for use on android.
.PP
.SH AUTHOR
Written by Olliver Schinagl.
.SH "REPORTING BUGS"
armStrapTools github support: <https://github.com/armStrapTools/sunxi-tools>
.SH COPYRIGHT
Copyright \(co 2015  Olliver Schinagl <oliver@schinagl.nl>
.PP
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.TP
sunxi-fexc(8), sunxi-bin2fex(8), sunxi-fex2bin(8), sunxi-nand-part(8), sunxi-bootinfo(8), sunxi-phoenix_info(8), sunxi-meminfo(8), sunxi-script_extractor(8), sunxi-pio(8). sunxi-fel(8), sunxi-baremetal(8)
