.TH SUNXI-BOOTINFO "8" "January 2016" "Sunxi-Tools for allWinner's devices"
.SH NAME
sunxi-bootinfo \- Dump information from Allwinner boot files (boot0/boot1)
.SH SYNOPSIS
.B sunxi-bootinfo
\fI--type\fR=<\fIsd\fR|\fInand\fR> <\fIFILENAME\fR> 
.PP
.SH DESCRIPTION
.\" Add any additional description here
.TP
\fB--type\fR=\fIsd\fR
include SD boot info
.TP
\fB--type\fR=\Finand\fR
include NAND boot info (not implemented)
.PP
.SH AUTHOR
Written by Henrik Nordstrom.
.SH "REPORTING BUGS"
armStrapTools github support: <https://github.com/armStrapTools/sunxi-tools>
.SH COPYRIGHT
Copyright \(co 2012 Henrik Nordstrom <henrik@henriknordstrom.net>
.PP
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.TP
sunxi-fexc(8), sunxi-bin2fex(8), sunxi-fex2bin(8), sunxi-nand-part(8), sunxi-bootinfo(8), sunxi-phoenix_info(8), sunxi-meminfo(8), sunxi-script_extractor(8), sunxi-pio(8). sunxi-fel(8), sunxi-baremetal(8)
