.TH SUNXI-MEMINFO "8" "January 2016" "Sunxi-Tools for allWinner's devices"
.SH NAME
sunxi-meminfo \- Tool for reading DRAM settings from registers. 
.SH SYNOPSIS
.TP
.B sunxi-meminfo [\fIOPTION\fR]
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
Tool for reading DRAM settings from registers.
.PP
Compiled as a static binary for use on android and other OSes.
.PP
.TP
\fB-f\fR
print in FEX format (default).
.TP
\fB-u\fR
print in sunxi U-Boot dram.c file format.
.TP
\fB-h\fR
print this usage information.
.PP
.SH AUTHOR
Written by Floris Bos and Luc Verhaegen.
.SH "REPORTING BUGS"
armStrapTools github support: <https://github.com/armStrapTools/sunxi-tools>
.SH COPYRIGHT
Copyright \(co 2012  Floris Bos <bos@je-eigen-domein.nl>
.br
Copyright \(co 2014  Luc Verhaegen <libv@skynet.be>
.PP
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.TP
sunxi-fexc(8), sunxi-bin2fex(8), sunxi-fex2bin(8), sunxi-nand-part(8), sunxi-bootinfo(8), sunxi-phoenix_info(8), sunxi-meminfo(8), sunxi-script_extractor(8), sunxi-pio(8). sunxi-fel(8), sunxi-baremetal(8)
