.TH SUNXI-FEX2BIN "8" "January 2016" "Sunxi-Tools for allWinner's devices"
.SH NAME
sunxi-fex2bin \- utility to compile fex format files used by Allwinners's sdk to configure board's options under kernel 3.4.
.SH SYNOPSIS
.B sunxi-fex2bin
[\fI-vq\fR] [<\fIfex file\fR> [<\fIbinary file\fR>]]
.PP
.SH DESCRIPTION
.\" Add any additional description here
.PP
.fex file compiler, utility to compile fex format files used by Allwinners's sdk to configure board's options under kernel 3.4.
.PP
.TP
\fB-v\fR
Verbose mode
.TP
\fB-q\fR
Quiet mode
.TP
\fBfex file\fR
Fex File.
.TP
\fBbinary file\fR
Binary File.
.PP
.SH AUTHOR
Written by Alejandro Mery.
.SH "REPORTING BUGS"
armStrapTools github support: <https://github.com/armStrapTools/sunxi-tools>
.SH COPYRIGHT
Copyright \(co 2012       Alejandro Mery <amery@geeks.cl>
.PP
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.TP
sunxi-fexc(8), sunxi-bin2fex(8), sunxi-fex2bin(8), sunxi-nand-part(8), sunxi-bootinfo(8), sunxi-phoenix_info(8), sunxi-meminfo(8), sunxi-script_extractor(8), sunxi-pio(8). sunxi-fel(8), sunxi-baremetal(8)
